
require('dotenv').config();
const { createClient } = require('@supabase/supabase-js');

const supabase = createClient(
  process.env.SUPABASE_URL,
  process.env.SUPABASE_SERVICE_KEY  // use service key, not anon key
);
// ============================================================
// 1. INVESTORS (25 real investors)
// ============================================================
const investors = [
  {
    name: 'Andreessen Horowitz',
    slug: 'andreessen-horowitz',
    type: 'VC',
    bio: 'Silicon Valley venture capital firm founded in 2009. One of the most active AI investors globally.',
    aum: 35000000000,
    portfolio_count: 500,
    stage_focus: ['seed', 'series-a', 'series-b', 'growth'],
    sector_focus: ['AI', 'FinTech', 'Crypto', 'Bio'],
    location: 'Menlo Park, CA',
    avg_check_size: 50000000,
    fund_number: 9,
    website: 'https://a16z.com',
    twitter: '@a16z',
  },
  {
    name: 'Sequoia Capital',
    slug: 'sequoia-capital',
    type: 'VC',
    bio: 'Legendary VC firm behind Apple, Google, and dozens of AI companies. Known for long-term conviction bets.',
    aum: 85000000000,
    portfolio_count: 1500,
    stage_focus: ['seed', 'series-a', 'series-b', 'series-c', 'growth'],
    sector_focus: ['AI', 'SaaS', 'FinTech', 'Consumer'],
    location: 'Menlo Park, CA',
    avg_check_size: 100000000,
    fund_number: 22,
    website: 'https://sequoiacap.com',
    twitter: '@sequoia',
  },
  {
    name: 'Y Combinator',
    slug: 'y-combinator',
    type: 'Accelerator',
    bio: 'The world\'s most prestigious startup accelerator. Alumni include Airbnb, Stripe, OpenAI, and thousands more.',
    aum: 1000000000,
    portfolio_count: 4000,
    stage_focus: ['pre-seed', 'seed'],
    sector_focus: ['AI', 'SaaS', 'FinTech', 'DevTools', 'Consumer'],
    location: 'San Francisco, CA',
    avg_check_size: 500000,
    fund_number: 39,
    website: 'https://ycombinator.com',
    twitter: '@ycombinator',
  },
  {
    name: 'Khosla Ventures',
    slug: 'khosla-ventures',
    type: 'VC',
    bio: 'Founded by Sun Microsystems co-founder Vinod Khosla. Deep focus on AI, health, and climate tech.',
    aum: 15000000000,
    portfolio_count: 300,
    stage_focus: ['seed', 'series-a', 'series-b'],
    sector_focus: ['AI', 'Health', 'Climate', 'Energy'],
    location: 'Menlo Park, CA',
    avg_check_size: 20000000,
    fund_number: 8,
    website: 'https://khoslaventures.com',
    twitter: '@khoslaventures',
  },
  {
    name: 'Tiger Global Management',
    slug: 'tiger-global',
    type: 'VC',
    bio: 'Global investment firm known for writing large checks fast. Active across AI, SaaS, and consumer internet.',
    aum: 50000000000,
    portfolio_count: 900,
    stage_focus: ['series-b', 'series-c', 'growth'],
    sector_focus: ['AI', 'SaaS', 'FinTech', 'E-commerce'],
    location: 'New York, NY',
    avg_check_size: 200000000,
    fund_number: 16,
    website: 'https://tigerglobal.com',
    twitter: '@tigerglobal',
  },
  {
    name: 'Microsoft Ventures',
    slug: 'microsoft-ventures',
    type: 'Corporate',
    bio: 'Microsoft\'s corporate venture arm. Made the landmark $13B investment in OpenAI.',
    aum: 10000000000,
    portfolio_count: 200,
    stage_focus: ['series-b', 'series-c', 'growth'],
    sector_focus: ['AI', 'Cloud', 'DevTools', 'SaaS'],
    location: 'Redmond, WA',
    avg_check_size: 500000000,
    fund_number: 1,
    website: 'https://microsoft.com',
    twitter: '@microsoft',
  },
  {
    name: 'Google Ventures',
    slug: 'google-ventures',
    type: 'Corporate',
    bio: 'Alphabet\'s independent venture fund. Early backer of AI companies across every stage.',
    aum: 8000000000,
    portfolio_count: 400,
    stage_focus: ['seed', 'series-a', 'series-b'],
    sector_focus: ['AI', 'Health', 'DevTools', 'Climate'],
    location: 'Mountain View, CA',
    avg_check_size: 25000000,
    fund_number: 3,
    website: 'https://gv.com',
    twitter: '@gv',
  },
  {
    name: 'Spark Capital',
    slug: 'spark-capital',
    type: 'VC',
    bio: 'Boston-based VC firm known for early bets on Twitter, Slack, and several AI companies.',
    aum: 5000000000,
    portfolio_count: 150,
    stage_focus: ['seed', 'series-a', 'series-b'],
    sector_focus: ['AI', 'SaaS', 'Consumer', 'FinTech'],
    location: 'Boston, MA',
    avg_check_size: 15000000,
    fund_number: 7,
    website: 'https://sparkcapital.com',
    twitter: '@sparkcapital',
  },
  {
    name: 'Coatue Management',
    slug: 'coatue-management',
    type: 'VC',
    bio: 'Technology-focused hedge fund and venture firm. Major backer of AI infrastructure companies.',
    aum: 50000000000,
    portfolio_count: 300,
    stage_focus: ['series-b', 'series-c', 'growth'],
    sector_focus: ['AI', 'SaaS', 'FinTech', 'Consumer'],
    location: 'New York, NY',
    avg_check_size: 100000000,
    fund_number: 5,
    website: 'https://coatue.com',
    twitter: '@coatue',
  },
  {
    name: 'Index Ventures',
    slug: 'index-ventures',
    type: 'VC',
    bio: 'European VC firm with strong US presence. Backed Figma, Notion, and several AI startups.',
    aum: 12000000000,
    portfolio_count: 350,
    stage_focus: ['seed', 'series-a', 'series-b'],
    sector_focus: ['AI', 'SaaS', 'FinTech', 'Gaming'],
    location: 'London, UK',
    avg_check_size: 30000000,
    fund_number: 10,
    website: 'https://indexventures.com',
    twitter: '@indexventures',
  },
  {
    name: 'Lightspeed Venture Partners',
    slug: 'lightspeed-venture-partners',
    type: 'VC',
    bio: 'Multi-stage VC with global presence. Early backer of Snap, Affirm, and AI infrastructure plays.',
    aum: 25000000000,
    portfolio_count: 500,
    stage_focus: ['seed', 'series-a', 'series-b', 'growth'],
    sector_focus: ['AI', 'Enterprise', 'Consumer', 'FinTech'],
    location: 'Menlo Park, CA',
    avg_check_size: 40000000,
    fund_number: 13,
    website: 'https://lsvp.com',
    twitter: '@lightspeedvp',
  },
  {
    name: 'Accel',
    slug: 'accel',
    type: 'VC',
    bio: 'Global VC firm with offices in Palo Alto, London, and Bangalore. Early Facebook investor.',
    aum: 20000000000,
    portfolio_count: 600,
    stage_focus: ['seed', 'series-a', 'series-b'],
    sector_focus: ['AI', 'SaaS', 'Security', 'FinTech'],
    location: 'Palo Alto, CA',
    avg_check_size: 25000000,
    fund_number: 15,
    website: 'https://accel.com',
    twitter: '@accel',
  },
  {
    name: 'General Catalyst',
    slug: 'general-catalyst',
    type: 'VC',
    bio: 'Cambridge-based VC known for long-term founder partnerships. Big bets on AI and health tech.',
    aum: 20000000000,
    portfolio_count: 400,
    stage_focus: ['seed', 'series-a', 'series-b', 'growth'],
    sector_focus: ['AI', 'Health', 'FinTech', 'Climate'],
    location: 'Cambridge, MA',
    avg_check_size: 50000000,
    fund_number: 11,
    website: 'https://generalcatalyst.com',
    twitter: '@gcvp',
  },
  {
    name: 'Salesforce Ventures',
    slug: 'salesforce-ventures',
    type: 'Corporate',
    bio: 'Salesforce\'s strategic investment arm. Focused on enterprise AI and cloud software.',
    aum: 4000000000,
    portfolio_count: 250,
    stage_focus: ['series-a', 'series-b', 'series-c'],
    sector_focus: ['AI', 'Enterprise SaaS', 'CRM', 'DevTools'],
    location: 'San Francisco, CA',
    avg_check_size: 20000000,
    fund_number: 2,
    website: 'https://salesforce.com/ventures',
    twitter: '@salesforce',
  },
  {
    name: 'NEA',
    slug: 'nea',
    type: 'VC',
    bio: 'One of the world\'s largest and most active venture capital firms with 45+ years of history.',
    aum: 25000000000,
    portfolio_count: 900,
    stage_focus: ['seed', 'series-a', 'series-b', 'growth'],
    sector_focus: ['AI', 'Health', 'Enterprise', 'Consumer'],
    location: 'Chevy Chase, MD',
    avg_check_size: 30000000,
    fund_number: 18,
    website: 'https://nea.com',
    twitter: '@nea',
  },
  {
    name: 'Bessemer Venture Partners',
    slug: 'bessemer-venture-partners',
    type: 'VC',
    bio: 'America\'s oldest VC firm. Known for the Anti-Portfolio (passed on Apple, Google) and big AI bets.',
    aum: 20000000000,
    portfolio_count: 400,
    stage_focus: ['seed', 'series-a', 'series-b'],
    sector_focus: ['AI', 'Cloud', 'Security', 'FinTech'],
    location: 'San Francisco, CA',
    avg_check_size: 20000000,
    fund_number: 12,
    website: 'https://bvp.com',
    twitter: '@bvp',
  },
  {
    name: 'Founders Fund',
    slug: 'founders-fund',
    type: 'VC',
    bio: 'Peter Thiel\'s venture fund. Contrarian bets on deep tech, AI, and defense.',
    aum: 11000000000,
    portfolio_count: 200,
    stage_focus: ['seed', 'series-a', 'growth'],
    sector_focus: ['AI', 'Defense', 'Bio', 'Space'],
    location: 'San Francisco, CA',
    avg_check_size: 50000000,
    fund_number: 8,
    website: 'https://foundersfund.com',
    twitter: '@foundersfund',
  },
  {
    name: 'Insight Partners',
    slug: 'insight-partners',
    type: 'VC',
    bio: 'Growth-stage focused firm with deep expertise in scaling software companies globally.',
    aum: 90000000000,
    portfolio_count: 700,
    stage_focus: ['series-b', 'series-c', 'growth'],
    sector_focus: ['AI', 'SaaS', 'DevTools', 'Security'],
    location: 'New York, NY',
    avg_check_size: 150000000,
    fund_number: 13,
    website: 'https://insightpartners.com',
    twitter: '@insightpartners',
  },
  {
    name: 'Balderton Capital',
    slug: 'balderton-capital',
    type: 'VC',
    bio: 'Leading European early-stage VC. Focused on AI and deep tech coming out of Europe.',
    aum: 6000000000,
    portfolio_count: 250,
    stage_focus: ['seed', 'series-a', 'series-b'],
    sector_focus: ['AI', 'FinTech', 'SaaS', 'Consumer'],
    location: 'London, UK',
    avg_check_size: 15000000,
    fund_number: 9,
    website: 'https://balderton.com',
    twitter: '@balderton',
  },
  {
    name: 'SV Angel',
    slug: 'sv-angel',
    type: 'Angel',
    bio: 'Seed-stage fund by Ron Conway. One of Silicon Valley\'s most prolific angel investors.',
    aum: 500000000,
    portfolio_count: 800,
    stage_focus: ['pre-seed', 'seed'],
    sector_focus: ['AI', 'Consumer', 'SaaS', 'FinTech'],
    location: 'San Francisco, CA',
    avg_check_size: 1000000,
    fund_number: 6,
    website: 'https://svangel.com',
    twitter: '@svangel',
  },
  {
    name: 'Felicis Ventures',
    slug: 'felicis-ventures',
    type: 'VC',
    bio: 'Early stage VC known for contrarian bets. Backed Fitbit, Shopify, and AI-first companies.',
    aum: 3000000000,
    portfolio_count: 200,
    stage_focus: ['seed', 'series-a'],
    sector_focus: ['AI', 'SaaS', 'Consumer', 'FinTech'],
    location: 'Menlo Park, CA',
    avg_check_size: 10000000,
    fund_number: 9,
    website: 'https://felicis.com',
    twitter: '@felicisventures',
  },
  {
    name: 'Greylock Partners',
    slug: 'greylock-partners',
    type: 'VC',
    bio: 'Storied VC firm behind LinkedIn, Airbnb, and Workday. Strong focus on AI developer tools.',
    aum: 20000000000,
    portfolio_count: 500,
    stage_focus: ['seed', 'series-a', 'series-b'],
    sector_focus: ['AI', 'Enterprise', 'Consumer', 'Security'],
    location: 'Menlo Park, CA',
    avg_check_size: 20000000,
    fund_number: 17,
    website: 'https://greylock.com',
    twitter: '@greylock',
  },
  {
    name: 'Benchmark',
    slug: 'benchmark',
    type: 'VC',
    bio: 'Small, focused VC with legendary returns. Early Uber, Twitter, Snap investor. Big on AI.',
    aum: 3000000000,
    portfolio_count: 150,
    stage_focus: ['seed', 'series-a'],
    sector_focus: ['AI', 'Consumer', 'SaaS', 'Marketplace'],
    location: 'San Francisco, CA',
    avg_check_size: 15000000,
    fund_number: 12,
    website: 'https://benchmark.com',
    twitter: '@benchmark',
  },
  {
    name: 'First Round Capital',
    slug: 'first-round-capital',
    type: 'VC',
    bio: 'Seed-stage VC known for its founder community. Early Square, Uber, and Notion investor.',
    aum: 3000000000,
    portfolio_count: 350,
    stage_focus: ['pre-seed', 'seed'],
    sector_focus: ['AI', 'SaaS', 'Consumer', 'FinTech'],
    location: 'San Francisco, CA',
    avg_check_size: 5000000,
    fund_number: 8,
    website: 'https://firstround.com',
    twitter: '@firstround',
  },
  {
    name: 'Nvidia Ventures',
    slug: 'nvidia-ventures',
    type: 'Corporate',
    bio: 'Nvidia\'s strategic investment arm focused on AI startups building on GPU infrastructure.',
    aum: 1000000000,
    portfolio_count: 100,
    stage_focus: ['series-a', 'series-b', 'series-c'],
    sector_focus: ['AI', 'Robotics', 'Autonomous Vehicles', 'Healthcare AI'],
    location: 'Santa Clara, CA',
    avg_check_size: 10000000,
    fund_number: 1,
    website: 'https://nvidia.com',
    twitter: '@nvidia',
  },
];

// ============================================================
// 2. COMPANIES (55 real AI companies)
// ============================================================
const companies = [
  {
    name: 'OpenAI',
    slug: 'openai',
    description: 'AI safety company building general-purpose AI. Creator of ChatGPT, GPT-4, DALL-E, and Sora.',
    category: 'LLM',
    stage: 'growth',
    funding_total: 11300000000,
    valuation: 80000000000,
    employee_count: 1800,
    founded_year: 2015,
    hq_city: 'San Francisco',
    hq_country: 'USA',
    website: 'https://openai.com',
    is_unicorn: true,
    growth_score: 98,
    data_confidence_score: 99,
  },
  {
    name: 'Anthropic',
    slug: 'anthropic',
    description: 'AI safety company and creator of Claude, a family of large language models focused on safety and helpfulness.',
    category: 'LLM',
    stage: 'series-d+',
    funding_total: 7300000000,
    valuation: 18000000000,
    employee_count: 800,
    founded_year: 2021,
    hq_city: 'San Francisco',
    hq_country: 'USA',
    website: 'https://anthropic.com',
    is_unicorn: true,
    growth_score: 95,
    data_confidence_score: 97,
  },
  {
    name: 'Mistral AI',
    slug: 'mistral-ai',
    description: 'French AI company building open-weight and proprietary LLMs. Known for efficient, high-performance models.',
    category: 'LLM',
    stage: 'series-b',
    funding_total: 1050000000,
    valuation: 6000000000,
    employee_count: 200,
    founded_year: 2023,
    hq_city: 'Paris',
    hq_country: 'France',
    website: 'https://mistral.ai',
    is_unicorn: true,
    growth_score: 90,
    data_confidence_score: 88,
  },
  {
    name: 'Cohere',
    slug: 'cohere',
    description: 'Enterprise AI platform providing LLMs for search, generation, and classification at scale.',
    category: 'LLM',
    stage: 'series-c',
    funding_total: 870000000,
    valuation: 5000000000,
    employee_count: 500,
    founded_year: 2019,
    hq_city: 'Toronto',
    hq_country: 'Canada',
    website: 'https://cohere.com',
    is_unicorn: true,
    growth_score: 82,
    data_confidence_score: 90,
  },
  {
    name: 'Hugging Face',
    slug: 'hugging-face',
    description: 'The AI community platform. Home to 500,000+ models, datasets, and the Transformers library.',
    category: 'AI Platform',
    stage: 'series-d+',
    funding_total: 395000000,
    valuation: 4500000000,
    employee_count: 350,
    founded_year: 2016,
    hq_city: 'New York',
    hq_country: 'USA',
    website: 'https://huggingface.co',
    is_unicorn: true,
    growth_score: 88,
    data_confidence_score: 92,
  },
  {
    name: 'Scale AI',
    slug: 'scale-ai',
    description: 'Data labeling and AI training data platform. Powers the training pipelines of major AI labs.',
    category: 'AI Infrastructure',
    stage: 'series-f+',
    funding_total: 1500000000,
    valuation: 14000000000,
    employee_count: 1200,
    founded_year: 2016,
    hq_city: 'San Francisco',
    hq_country: 'USA',
    website: 'https://scale.com',
    is_unicorn: true,
    growth_score: 85,
    data_confidence_score: 91,
  },
  {
    name: 'Stability AI',
    slug: 'stability-ai',
    description: 'Creator of Stable Diffusion, the open-source image generation model. Pioneer of open generative AI.',
    category: 'Image Generation',
    stage: 'series-b',
    funding_total: 101000000,
    valuation: 1000000000,
    employee_count: 150,
    founded_year: 2019,
    hq_city: 'London',
    hq_country: 'UK',
    website: 'https://stability.ai',
    is_unicorn: true,
    growth_score: 60,
    data_confidence_score: 80,
  },
  {
    name: 'Midjourney',
    slug: 'midjourney',
    description: 'Independent AI image generation lab. Known for photorealistic and artistic image synthesis via Discord.',
    category: 'Image Generation',
    stage: 'growth',
    funding_total: 0,
    valuation: 10000000000,
    employee_count: 40,
    founded_year: 2021,
    hq_city: 'San Francisco',
    hq_country: 'USA',
    website: 'https://midjourney.com',
    is_unicorn: true,
    growth_score: 87,
    data_confidence_score: 70,
  },
  {
    name: 'Runway',
    slug: 'runway',
    description: 'AI video generation and creative tools platform. Creator of Gen-2 video model.',
    category: 'Video Generation',
    stage: 'series-c',
    funding_total: 237000000,
    valuation: 1500000000,
    employee_count: 180,
    founded_year: 2018,
    hq_city: 'New York',
    hq_country: 'USA',
    website: 'https://runwayml.com',
    is_unicorn: true,
    growth_score: 83,
    data_confidence_score: 86,
  },
  {
    name: 'Perplexity AI',
    slug: 'perplexity-ai',
    description: 'AI-powered answer engine that provides cited, real-time answers to any question.',
    category: 'Search AI',
    stage: 'series-b',
    funding_total: 165000000,
    valuation: 1000000000,
    employee_count: 100,
    founded_year: 2022,
    hq_city: 'San Francisco',
    hq_country: 'USA',
    website: 'https://perplexity.ai',
    is_unicorn: true,
    growth_score: 91,
    data_confidence_score: 85,
  },
  {
    name: 'Character AI',
    slug: 'character-ai',
    description: 'Consumer AI chatbot platform enabling conversations with AI personas. Massive teen user base.',
    category: 'Consumer AI',
    stage: 'series-b',
    funding_total: 150000000,
    valuation: 1000000000,
    employee_count: 200,
    founded_year: 2021,
    hq_city: 'Menlo Park',
    hq_country: 'USA',
    website: 'https://character.ai',
    is_unicorn: true,
    growth_score: 78,
    data_confidence_score: 82,
  },
  {
    name: 'Inflection AI',
    slug: 'inflection-ai',
    description: 'AI company building Pi, a personal AI designed for emotionally intelligent conversation.',
    category: 'Consumer AI',
    stage: 'series-b',
    funding_total: 1525000000,
    valuation: 4000000000,
    employee_count: 200,
    founded_year: 2022,
    hq_city: 'Palo Alto',
    hq_country: 'USA',
    website: 'https://inflection.ai',
    is_unicorn: true,
    growth_score: 65,
    data_confidence_score: 80,
  },
  {
    name: 'Adept AI',
    slug: 'adept-ai',
    description: 'Building AI agents that can take actions on computers. Focused on enterprise workflow automation.',
    category: 'AI Agents',
    stage: 'series-b',
    funding_total: 415000000,
    valuation: 1000000000,
    employee_count: 100,
    founded_year: 2022,
    hq_city: 'San Francisco',
    hq_country: 'USA',
    website: 'https://adept.ai',
    is_unicorn: true,
    growth_score: 72,
    data_confidence_score: 78,
  },
  {
    name: 'Imbue',
    slug: 'imbue',
    description: 'AI research lab focused on building AI systems that can reason and code autonomously.',
    category: 'AI Research',
    stage: 'series-b',
    funding_total: 220000000,
    valuation: 1000000000,
    employee_count: 80,
    founded_year: 2021,
    hq_city: 'San Francisco',
    hq_country: 'USA',
    website: 'https://imbue.com',
    is_unicorn: true,
    growth_score: 68,
    data_confidence_score: 72,
  },
  {
    name: 'Together AI',
    slug: 'together-ai',
    description: 'Cloud platform for training and running open-source AI models at scale. Fast inference API.',
    category: 'AI Infrastructure',
    stage: 'series-a',
    funding_total: 102500000,
    valuation: 500000000,
    employee_count: 80,
    founded_year: 2022,
    hq_city: 'San Francisco',
    hq_country: 'USA',
    website: 'https://together.ai',
    is_unicorn: false,
    growth_score: 79,
    data_confidence_score: 83,
  },
  {
    name: 'Replicate',
    slug: 'replicate',
    description: 'Cloud platform to run open-source machine learning models via API with one line of code.',
    category: 'AI Infrastructure',
    stage: 'series-b',
    funding_total: 40000000,
    valuation: 350000000,
    employee_count: 50,
    founded_year: 2019,
    hq_city: 'San Francisco',
    hq_country: 'USA',
    website: 'https://replicate.com',
    is_unicorn: false,
    growth_score: 75,
    data_confidence_score: 80,
  },
  {
    name: 'Weights & Biases',
    slug: 'weights-and-biases',
    description: 'MLOps platform for tracking, visualizing, and reproducing machine learning experiments.',
    category: 'MLOps',
    stage: 'series-c',
    funding_total: 200000000,
    valuation: 1250000000,
    employee_count: 600,
    founded_year: 2018,
    hq_city: 'San Francisco',
    hq_country: 'USA',
    website: 'https://wandb.ai',
    is_unicorn: true,
    growth_score: 80,
    data_confidence_score: 88,
  },
  {
    name: 'LangChain',
    slug: 'langchain',
    description: 'Open-source framework for building LLM-powered applications. Most popular AI dev tool.',
    category: 'DevTools',
    stage: 'series-a',
    funding_total: 35000000,
    valuation: 200000000,
    employee_count: 60,
    founded_year: 2022,
    hq_city: 'San Francisco',
    hq_country: 'USA',
    website: 'https://langchain.com',
    is_unicorn: false,
    growth_score: 85,
    data_confidence_score: 82,
  },
  {
    name: 'Pinecone',
    slug: 'pinecone',
    description: 'Managed vector database built for AI applications. Powers semantic search and RAG pipelines.',
    category: 'AI Infrastructure',
    stage: 'series-b',
    funding_total: 138000000,
    valuation: 750000000,
    employee_count: 200,
    founded_year: 2019,
    hq_city: 'New York',
    hq_country: 'USA',
    website: 'https://pinecone.io',
    is_unicorn: false,
    growth_score: 82,
    data_confidence_score: 87,
  },
  {
    name: 'Weaviate',
    slug: 'weaviate',
    description: 'Open-source vector database that stores both objects and vectors for AI-native applications.',
    category: 'AI Infrastructure',
    stage: 'series-b',
    funding_total: 68000000,
    valuation: 400000000,
    employee_count: 120,
    founded_year: 2019,
    hq_city: 'Amsterdam',
    hq_country: 'Netherlands',
    website: 'https://weaviate.io',
    is_unicorn: false,
    growth_score: 76,
    data_confidence_score: 83,
  },
  {
    name: 'Anyscale',
    slug: 'anyscale',
    description: 'Company behind Ray, the open-source framework for scaling AI workloads. Enterprise AI compute.',
    category: 'AI Infrastructure',
    stage: 'series-c',
    funding_total: 259000000,
    valuation: 1000000000,
    employee_count: 300,
    founded_year: 2019,
    hq_city: 'San Francisco',
    hq_country: 'USA',
    website: 'https://anyscale.com',
    is_unicorn: true,
    growth_score: 77,
    data_confidence_score: 84,
  },
  {
    name: 'Modal',
    slug: 'modal',
    description: 'Cloud platform for running AI inference and training workloads with simple Python decorators.',
    category: 'AI Infrastructure',
    stage: 'series-a',
    funding_total: 25000000,
    valuation: 150000000,
    employee_count: 40,
    founded_year: 2021,
    hq_city: 'New York',
    hq_country: 'USA',
    website: 'https://modal.com',
    is_unicorn: false,
    growth_score: 73,
    data_confidence_score: 78,
  },
  {
    name: 'Cursor',
    slug: 'cursor',
    description: 'AI-first code editor built on VS Code. Uses LLMs to autocomplete, explain, and edit code.',
    category: 'DevTools',
    stage: 'series-a',
    funding_total: 60000000,
    valuation: 400000000,
    employee_count: 50,
    founded_year: 2022,
    hq_city: 'San Francisco',
    hq_country: 'USA',
    website: 'https://cursor.com',
    is_unicorn: false,
    growth_score: 92,
    data_confidence_score: 85,
  },
  {
    name: 'Replit',
    slug: 'replit',
    description: 'Browser-based IDE with AI coding assistant. Used by 30M+ developers worldwide.',
    category: 'DevTools',
    stage: 'series-b',
    funding_total: 222000000,
    valuation: 1160000000,
    employee_count: 200,
    founded_year: 2016,
    hq_city: 'San Francisco',
    hq_country: 'USA',
    website: 'https://replit.com',
    is_unicorn: true,
    growth_score: 80,
    data_confidence_score: 86,
  },
  {
    name: 'Coreweave',
    slug: 'coreweave',
    description: 'Specialized cloud provider offering GPU compute for AI workloads. Nvidia-backed.',
    category: 'AI Infrastructure',
    stage: 'series-c',
    funding_total: 2300000000,
    valuation: 19000000000,
    employee_count: 800,
    founded_year: 2017,
    hq_city: 'Livingston',
    hq_country: 'USA',
    website: 'https://coreweave.com',
    is_unicorn: true,
    growth_score: 88,
    data_confidence_score: 87,
  },
  {
    name: 'Databricks',
    slug: 'databricks',
    description: 'Unified analytics platform combining data engineering and AI. Creator of MLflow and Delta Lake.',
    category: 'Data & AI',
    stage: 'series-i',
    funding_total: 3500000000,
    valuation: 43000000000,
    employee_count: 6000,
    founded_year: 2013,
    hq_city: 'San Francisco',
    hq_country: 'USA',
    website: 'https://databricks.com',
    is_unicorn: true,
    growth_score: 86,
    data_confidence_score: 94,
  },
  {
    name: 'Lightning AI',
    slug: 'lightning-ai',
    description: 'Platform for training and deploying AI models. Built on PyTorch Lightning.',
    category: 'MLOps',
    stage: 'series-b',
    funding_total: 58000000,
    valuation: 300000000,
    employee_count: 100,
    founded_year: 2019,
    hq_city: 'New York',
    hq_country: 'USA',
    website: 'https://lightning.ai',
    is_unicorn: false,
    growth_score: 71,
    data_confidence_score: 79,
  },
  {
    name: 'Twelve Labs',
    slug: 'twelve-labs',
    description: 'Video understanding AI. Enables semantic search and analysis inside video content.',
    category: 'Computer Vision',
    stage: 'series-a',
    funding_total: 27000000,
    valuation: 200000000,
    employee_count: 60,
    founded_year: 2021,
    hq_city: 'San Francisco',
    hq_country: 'USA',
    website: 'https://twelvelabs.io',
    is_unicorn: false,
    growth_score: 74,
    data_confidence_score: 77,
  },
  {
    name: 'Synthesia',
    slug: 'synthesia',
    description: 'AI video generation platform. Create videos with AI avatars from text in minutes.',
    category: 'Video Generation',
    stage: 'series-c',
    funding_total: 157000000,
    valuation: 1000000000,
    employee_count: 300,
    founded_year: 2017,
    hq_city: 'London',
    hq_country: 'UK',
    website: 'https://synthesia.io',
    is_unicorn: true,
    growth_score: 79,
    data_confidence_score: 86,
  },
  {
    name: 'ElevenLabs',
    slug: 'elevenlabs',
    description: 'AI voice synthesis and cloning platform. Produces the most realistic AI voices available.',
    category: 'Audio AI',
    stage: 'series-b',
    funding_total: 101000000,
    valuation: 1100000000,
    employee_count: 150,
    founded_year: 2022,
    hq_city: 'New York',
    hq_country: 'USA',
    website: 'https://elevenlabs.io',
    is_unicorn: true,
    growth_score: 89,
    data_confidence_score: 87,
  },
  {
    name: 'Otter.ai',
    slug: 'otter-ai',
    description: 'AI meeting assistant that records, transcribes, and summarizes meetings in real time.',
    category: 'Productivity AI',
    stage: 'series-b',
    funding_total: 63000000,
    valuation: 500000000,
    employee_count: 200,
    founded_year: 2016,
    hq_city: 'Mountain View',
    hq_country: 'USA',
    website: 'https://otter.ai',
    is_unicorn: false,
    growth_score: 70,
    data_confidence_score: 82,
  },
  {
    name: 'Notion AI',
    slug: 'notion-ai',
    description: 'AI features built into Notion workspace. Summarize, draft, translate content inside your docs.',
    category: 'Productivity AI',
    stage: 'growth',
    funding_total: 343000000,
    valuation: 10000000000,
    employee_count: 500,
    founded_year: 2016,
    hq_city: 'San Francisco',
    hq_country: 'USA',
    website: 'https://notion.so',
    is_unicorn: true,
    growth_score: 81,
    data_confidence_score: 90,
  },
  {
    name: 'Glean',
    slug: 'glean',
    description: 'AI-powered enterprise search connecting all company apps and knowledge. Built by ex-Google engineers.',
    category: 'Enterprise AI',
    stage: 'series-d',
    funding_total: 360000000,
    valuation: 2200000000,
    employee_count: 500,
    founded_year: 2019,
    hq_city: 'Palo Alto',
    hq_country: 'USA',
    website: 'https://glean.com',
    is_unicorn: true,
    growth_score: 84,
    data_confidence_score: 86,
  },
  {
    name: 'Harvey AI',
    slug: 'harvey-ai',
    description: 'AI platform for law firms. Automates legal research, drafting, and document review.',
    category: 'Legal AI',
    stage: 'series-b',
    funding_total: 206000000,
    valuation: 1500000000,
    employee_count: 200,
    founded_year: 2022,
    hq_city: 'San Francisco',
    hq_country: 'USA',
    website: 'https://harvey.ai',
    is_unicorn: true,
    growth_score: 86,
    data_confidence_score: 83,
  },
  {
    name: 'Jasper AI',
    slug: 'jasper-ai',
    description: 'AI content platform for marketing teams. Generates on-brand copy, blogs, and social posts.',
    category: 'Content AI',
    stage: 'series-a',
    funding_total: 131000000,
    valuation: 1500000000,
    employee_count: 400,
    founded_year: 2021,
    hq_city: 'Austin',
    hq_country: 'USA',
    website: 'https://jasper.ai',
    is_unicorn: true,
    growth_score: 65,
    data_confidence_score: 85,
  },
  {
    name: 'Writer',
    slug: 'writer',
    description: 'Full-stack generative AI platform for enterprises. Deploy AI with company knowledge and style.',
    category: 'Enterprise AI',
    stage: 'series-b',
    funding_total: 200000000,
    valuation: 1900000000,
    employee_count: 300,
    founded_year: 2020,
    hq_city: 'San Francisco',
    hq_country: 'USA',
    website: 'https://writer.com',
    is_unicorn: true,
    growth_score: 80,
    data_confidence_score: 84,
  },
  {
    name: 'Typeface',
    slug: 'typeface',
    description: 'Generative AI app for enterprise content creation with brand guardrails.',
    category: 'Content AI',
    stage: 'series-b',
    funding_total: 165000000,
    valuation: 1000000000,
    employee_count: 150,
    founded_year: 2022,
    hq_city: 'San Francisco',
    hq_country: 'USA',
    website: 'https://typeface.ai',
    is_unicorn: true,
    growth_score: 72,
    data_confidence_score: 79,
  },
  {
    name: 'Tome',
    slug: 'tome',
    description: 'AI-powered presentation tool. Generate full slide decks from a prompt in seconds.',
    category: 'Productivity AI',
    stage: 'series-b',
    funding_total: 81000000,
    valuation: 300000000,
    employee_count: 80,
    founded_year: 2020,
    hq_city: 'San Francisco',
    hq_country: 'USA',
    website: 'https://tome.app',
    is_unicorn: false,
    growth_score: 68,
    data_confidence_score: 78,
  },
  {
    name: 'Descript',
    slug: 'descript',
    description: 'AI video and podcast editing tool. Edit media by editing the transcript like a doc.',
    category: 'Audio AI',
    stage: 'series-c',
    funding_total: 100000000,
    valuation: 550000000,
    employee_count: 200,
    founded_year: 2017,
    hq_city: 'San Francisco',
    hq_country: 'USA',
    website: 'https://descript.com',
    is_unicorn: false,
    growth_score: 74,
    data_confidence_score: 83,
  },
  {
    name: 'Sierra AI',
    slug: 'sierra-ai',
    description: 'Conversational AI platform for customer experience. Built by ex-Salesforce and Google executives.',
    category: 'Enterprise AI',
    stage: 'series-b',
    funding_total: 110000000,
    valuation: 1000000000,
    employee_count: 100,
    founded_year: 2023,
    hq_city: 'San Francisco',
    hq_country: 'USA',
    website: 'https://sierra.ai',
    is_unicorn: true,
    growth_score: 83,
    data_confidence_score: 77,
  },
  {
    name: 'Moonshot AI',
    slug: 'moonshot-ai',
    description: 'Chinese AI company behind Kimi, a long-context LLM supporting 1M token windows.',
    category: 'LLM',
    stage: 'series-b',
    funding_total: 1000000000,
    valuation: 3300000000,
    employee_count: 300,
    founded_year: 2023,
    hq_city: 'Beijing',
    hq_country: 'China',
    website: 'https://moonshot.cn',
    is_unicorn: true,
    growth_score: 85,
    data_confidence_score: 75,
  },
  {
    name: 'DeepSeek',
    slug: 'deepseek',
    description: 'Chinese AI lab releasing open-weight models that rival GPT-4 at a fraction of the cost.',
    category: 'LLM',
    stage: 'growth',
    funding_total: 0,
    valuation: null,
    employee_count: 200,
    founded_year: 2023,
    hq_city: 'Hangzhou',
    hq_country: 'China',
    website: 'https://deepseek.com',
    is_unicorn: false,
    growth_score: 93,
    data_confidence_score: 70,
  },
  {
    name: 'xAI',
    slug: 'xai',
    description: 'Elon Musk\'s AI company. Creator of Grok, an LLM integrated with X (Twitter).',
    category: 'LLM',
    stage: 'series-b',
    funding_total: 6000000000,
    valuation: 18000000000,
    employee_count: 400,
    founded_year: 2023,
    hq_city: 'San Francisco',
    hq_country: 'USA',
    website: 'https://x.ai',
    is_unicorn: true,
    growth_score: 87,
    data_confidence_score: 78,
  },
  {
    name: 'Aleph Alpha',
    slug: 'aleph-alpha',
    description: 'European sovereign AI company. Builds LLMs for the EU with a focus on privacy and compliance.',
    category: 'LLM',
    stage: 'series-b',
    funding_total: 500000000,
    valuation: 500000000,
    employee_count: 250,
    founded_year: 2019,
    hq_city: 'Heidelberg',
    hq_country: 'Germany',
    website: 'https://aleph-alpha.com',
    is_unicorn: false,
    growth_score: 69,
    data_confidence_score: 80,
  },
  {
    name: 'AI21 Labs',
    slug: 'ai21-labs',
    description: 'Israeli AI company building Jurassic LLMs and Wordtune writing assistant.',
    category: 'LLM',
    stage: 'series-c',
    funding_total: 336000000,
    valuation: 1400000000,
    employee_count: 250,
    founded_year: 2017,
    hq_city: 'Tel Aviv',
    hq_country: 'Israel',
    website: 'https://ai21.com',
    is_unicorn: true,
    growth_score: 70,
    data_confidence_score: 83,
  },
  {
    name: 'Luma AI',
    slug: 'luma-ai',
    description: 'AI video and 3D generation. Known for Dream Machine video generation and NeRF capture.',
    category: 'Video Generation',
    stage: 'series-b',
    funding_total: 43000000,
    valuation: 200000000,
    employee_count: 60,
    founded_year: 2021,
    hq_city: 'San Francisco',
    hq_country: 'USA',
    website: 'https://lumalabs.ai',
    is_unicorn: false,
    growth_score: 80,
    data_confidence_score: 78,
  },
  {
    name: 'Galileo AI',
    slug: 'galileo-ai',
    description: 'AI UI design tool. Generate Figma-ready UI designs from text descriptions instantly.',
    category: 'Design AI',
    stage: 'seed',
    funding_total: 4000000,
    valuation: 30000000,
    employee_count: 20,
    founded_year: 2022,
    hq_city: 'San Francisco',
    hq_country: 'USA',
    website: 'https://usegalileo.ai',
    is_unicorn: false,
    growth_score: 66,
    data_confidence_score: 72,
  },
  {
    name: 'Fixie AI',
    slug: 'fixie-ai',
    description: 'Platform for building AI agents that interact with APIs, data, and real-world tools.',
    category: 'AI Agents',
    stage: 'seed',
    funding_total: 17000000,
    valuation: 100000000,
    employee_count: 30,
    founded_year: 2022,
    hq_city: 'Seattle',
    hq_country: 'USA',
    website: 'https://fixie.ai',
    is_unicorn: false,
    growth_score: 64,
    data_confidence_score: 73,
  },
  {
    name: 'Vapi AI',
    slug: 'vapi-ai',
    description: 'Voice AI infrastructure for developers. Build and deploy voice agents with any LLM.',
    category: 'Audio AI',
    stage: 'seed',
    funding_total: 20000000,
    valuation: 120000000,
    employee_count: 25,
    founded_year: 2023,
    hq_city: 'San Francisco',
    hq_country: 'USA',
    website: 'https://vapi.ai',
    is_unicorn: false,
    growth_score: 77,
    data_confidence_score: 74,
  },
  {
    name: 'Dust',
    slug: 'dust',
    description: 'AI assistants for teams built on your company data. Deploy custom LLM agents with connectors.',
    category: 'Enterprise AI',
    stage: 'series-a',
    funding_total: 16000000,
    valuation: 80000000,
    employee_count: 20,
    founded_year: 2022,
    hq_city: 'Paris',
    hq_country: 'France',
    website: 'https://dust.tt',
    is_unicorn: false,
    growth_score: 69,
    data_confidence_score: 75,
  },
  {
    name: 'Codeium',
    slug: 'codeium',
    description: 'Free AI code completion tool supporting 70+ languages. GitHub Copilot alternative.',
    category: 'DevTools',
    stage: 'series-c',
    funding_total: 93000000,
    valuation: 500000000,
    employee_count: 100,
    founded_year: 2021,
    hq_city: 'Mountain View',
    hq_country: 'USA',
    website: 'https://codeium.com',
    is_unicorn: false,
    growth_score: 82,
    data_confidence_score: 84,
  },
  {
    name: 'Tabnine',
    slug: 'tabnine',
    description: 'AI code assistant with privacy-first approach. Runs locally or in private cloud.',
    category: 'DevTools',
    stage: 'series-b',
    funding_total: 52000000,
    valuation: 250000000,
    employee_count: 150,
    founded_year: 2017,
    hq_city: 'Tel Aviv',
    hq_country: 'Israel',
    website: 'https://tabnine.com',
    is_unicorn: false,
    growth_score: 68,
    data_confidence_score: 82,
  },
  {
    name: 'Pika Labs',
    slug: 'pika-labs',
    description: 'AI video generation startup. Create and edit videos from text or image with simple prompts.',
    category: 'Video Generation',
    stage: 'series-a',
    funding_total: 55000000,
    valuation: 500000000,
    employee_count: 30,
    founded_year: 2023,
    hq_city: 'Palo Alto',
    hq_country: 'USA',
    website: 'https://pika.art',
    is_unicorn: false,
    growth_score: 81,
    data_confidence_score: 76,
  },
];

// ============================================================
// SEED FUNCTION
// ============================================================
async function seed() {
  console.log('🌱 Starting GraphOne seed...\n');

  // --- Insert Investors ---
  console.log('📥 Inserting investors...');
  const { data: investorRows, error: invErr } = await supabase
    .from('investors')
    .insert(investors)
    .select();
  if (invErr) { console.error('❌ Investors error:', invErr.message); process.exit(1); }
  console.log(`✅ Inserted ${investorRows.length} investors`);

  // Build slug → id map for easy lookup
  const investorMap = {};
  investorRows.forEach(inv => { investorMap[inv.slug] = inv.id; });

  // --- Insert Companies ---
  console.log('\n📥 Inserting companies...');
  const { data: companyRows, error: coErr } = await supabase
    .from('companies')
    .insert(companies)
    .select();
  if (coErr) { console.error('❌ Companies error:', coErr.message); process.exit(1); }
  console.log(`✅ Inserted ${companyRows.length} companies`);

  // Build slug → id map
  const companyMap = {};
  companyRows.forEach(co => { companyMap[co.slug] = co.id; });

  // --- Insert Founders ---
  console.log('\n📥 Inserting founders...');
  const founders = [
    { name: 'Sam Altman',       slug: 'sam-altman',       title: 'CEO & Co-Founder',      company_id: companyMap['openai'],          bio: 'Previously president of Y Combinator. One of the most influential figures in AI.',  linkedin: 'samaltman',       twitter: '@sama',          location: 'San Francisco, CA' },
    { name: 'Greg Brockman',    slug: 'greg-brockman',    title: 'President & Co-Founder', company_id: companyMap['openai'],          bio: 'Ex-CTO of Stripe. Co-founded OpenAI with Sam Altman.',                              linkedin: 'gregbrockman',    twitter: '@gdb',           location: 'San Francisco, CA' },
    { name: 'Dario Amodei',     slug: 'dario-amodei',     title: 'CEO & Co-Founder',       company_id: companyMap['anthropic'],       bio: 'Former VP of Research at OpenAI. Leading AI safety research at Anthropic.',         linkedin: 'darioamodei',     twitter: '@DarioAmodei',   location: 'San Francisco, CA' },
    { name: 'Daniela Amodei',   slug: 'daniela-amodei',   title: 'President & Co-Founder', company_id: companyMap['anthropic'],       bio: 'Former VP of Operations at OpenAI. Co-founder of Anthropic.',                       linkedin: 'danielaamodei',   twitter: '@danielaamodei', location: 'San Francisco, CA' },
    { name: 'Arthur Mensch',    slug: 'arthur-mensch',    title: 'CEO & Co-Founder',       company_id: companyMap['mistral-ai'],      bio: 'Ex-DeepMind researcher. Co-founded Mistral AI to build efficient open models.',      linkedin: 'arthurmensch',    twitter: '@arthurmensch',  location: 'Paris, France'     },
    { name: 'Aidan Gomez',      slug: 'aidan-gomez',      title: 'CEO & Co-Founder',       company_id: companyMap['cohere'],          bio: 'Co-author of the original Transformer paper. Founded Cohere at 22.',                 linkedin: 'aidangomez',      twitter: '@aidangomez',    location: 'Toronto, Canada'   },
    { name: 'Clement Delangue', slug: 'clement-delangue', title: 'CEO & Co-Founder',       company_id: companyMap['hugging-face'],    bio: 'Built Hugging Face from a chatbot app into the GitHub of AI.',                      linkedin: 'clementdelangue', twitter: '@clmt',          location: 'New York, NY'      },
    { name: 'Alexandr Wang',    slug: 'alexandr-wang',    title: 'CEO & Founder',          company_id: companyMap['scale-ai'],        bio: 'Founded Scale AI at 19. Youngest self-made billionaire in the USA.',                 linkedin: 'alexandrwang',    twitter: '@alexandr_wang', location: 'San Francisco, CA' },
    { name: 'Emad Mostaque',    slug: 'emad-mostaque',    title: 'Founder',                company_id: companyMap['stability-ai'],    bio: 'Founded Stability AI and released Stable Diffusion as open source.',                 linkedin: 'emadmostaque',    twitter: '@EMostaque',     location: 'London, UK'        },
    { name: 'Cristóbal Valenzuela', slug: 'cristobal-valenzuela', title: 'CEO & Co-Founder', company_id: companyMap['runway'],       bio: 'Chilean entrepreneur who built Runway into the leading AI video company.',           linkedin: 'crisvalenzuela',  twitter: '@c_valenzuela',  location: 'New York, NY'      },
    { name: 'Aravind Srinivas', slug: 'aravind-srinivas', title: 'CEO & Co-Founder',       company_id: companyMap['perplexity-ai'],   bio: 'Ex-OpenAI and DeepMind researcher. Building the AI-native search engine.',          linkedin: 'aravindsrinivas', twitter: '@AravSrinivas',  location: 'San Francisco, CA' },
    { name: 'Noam Shazeer',     slug: 'noam-shazeer',     title: 'CEO & Co-Founder',       company_id: companyMap['character-ai'],   bio: 'Co-inventor of the Transformer. Left Google to build Character.AI.',                linkedin: 'noamshazeer',     twitter: '@noamshazeer',   location: 'Menlo Park, CA'    },
    { name: 'Mustafa Suleyman', slug: 'mustafa-suleyman', title: 'CEO & Co-Founder',       company_id: companyMap['inflection-ai'],   bio: 'Co-founder of DeepMind. Founded Inflection AI, later joined Microsoft.',            linkedin: 'mustafasuleyman', twitter: '@mustafasuleyman',location: 'Palo Alto, CA'     },
    { name: 'Matan Danos',      slug: 'matan-danos',      title: 'CEO & Co-Founder',       company_id: companyMap['together-ai'],    bio: 'Building the open-source AI cloud at Together.',                                    linkedin: 'matandanos',      twitter: '@matandanos',    location: 'San Francisco, CA' },
    { name: 'Harrison Chase',   slug: 'harrison-chase',   title: 'CEO & Co-Founder',       company_id: companyMap['langchain'],      bio: 'Created LangChain as a side project. Now runs the most popular AI dev framework.',  linkedin: 'harrisonchase',   twitter: '@hwchase17',     location: 'San Francisco, CA' },
    { name: 'Michael Truell',   slug: 'michael-truell',   title: 'CEO & Co-Founder',       company_id: companyMap['cursor'],         bio: 'Ex-Jane Street. Co-founded Cursor to build the AI-first code editor.',              linkedin: 'michaeltruell',   twitter: '@michaeltruell',  location: 'San Francisco, CA' },
    { name: 'Mati Staniszewski',slug: 'mati-staniszewski',title: 'CEO & Co-Founder',       company_id: companyMap['elevenlabs'],     bio: 'Co-founded ElevenLabs to make voice AI sound indistinguishable from humans.',       linkedin: 'matisl',          twitter: '@mati_staniszewski',location:'New York, NY'     },
    { name: 'Arvid Lunnemark',  slug: 'arvid-lunnemark',  title: 'CEO & Co-Founder',       company_id: companyMap['codeium'],        bio: 'Built Codeium to offer free AI code completion for every developer.',               linkedin: 'arvidlunnemark',  twitter: '@arvidlunnemark', location: 'Mountain View, CA' },
    { name: 'Adam Coates',      slug: 'adam-coates',      title: 'CEO & Co-Founder',       company_id: companyMap['harvey-ai'],      bio: 'Ex-Baidu AI researcher. Applying LLMs to transform legal work.',                    linkedin: 'adamcoates',      twitter: '@adamcoates',    location: 'San Francisco, CA' },
    { name: 'Elon Musk',        slug: 'elon-musk',        title: 'Founder & CEO',          company_id: companyMap['xai'],            bio: 'Founder of Tesla, SpaceX, and xAI. Building Grok to understand the universe.',     linkedin: 'elonmusk',        twitter: '@elonmusk',      location: 'Austin, TX'        },
  ];

  const { data: founderRows, error: foErr } = await supabase
    .from('founders')
    .insert(founders)
    .select();
  if (foErr) { console.error('❌ Founders error:', foErr.message); process.exit(1); }
  console.log(`✅ Inserted ${founderRows.length} founders`);

  // --- Insert Products ---
  console.log('\n📥 Inserting products...');
  const products = [
    { company_id: companyMap['openai'],        name: 'ChatGPT',          slug: 'chatgpt',          description: 'Conversational AI chatbot used by 200M+ people.',          category: 'Chatbot',        launch_date: '2022-11-30', upvotes: 98000, website_url: 'https://chat.openai.com' },
    { company_id: companyMap['openai'],        name: 'GPT-4o',           slug: 'gpt-4o',           description: 'Flagship multimodal LLM supporting text, audio, and vision.', category: 'LLM API',       launch_date: '2024-05-13', upvotes: 72000, website_url: 'https://openai.com/gpt-4o' },
    { company_id: companyMap['openai'],        name: 'DALL-E 3',         slug: 'dall-e-3',         description: 'State-of-the-art text-to-image generation model.',            category: 'Image Gen',     launch_date: '2023-10-01', upvotes: 45000, website_url: 'https://openai.com/dall-e-3' },
    { company_id: companyMap['openai'],        name: 'Sora',             slug: 'sora',             description: 'Text-to-video model generating cinematic quality videos.',    category: 'Video Gen',     launch_date: '2024-02-15', upvotes: 88000, website_url: 'https://openai.com/sora' },
    { company_id: companyMap['anthropic'],     name: 'Claude 3.5 Sonnet',slug: 'claude-35-sonnet', description: 'Anthropic\'s most intelligent and capable model.',           category: 'LLM API',       launch_date: '2024-06-20', upvotes: 65000, website_url: 'https://anthropic.com/claude' },
    { company_id: companyMap['anthropic'],     name: 'Claude.ai',        slug: 'claude-ai',        description: 'Consumer chat interface powered by Claude models.',           category: 'Chatbot',       launch_date: '2023-07-11', upvotes: 42000, website_url: 'https://claude.ai' },
    { company_id: companyMap['mistral-ai'],    name: 'Mistral Large',    slug: 'mistral-large',    description: 'Flagship proprietary model rivaling GPT-4.',                 category: 'LLM API',       launch_date: '2024-02-26', upvotes: 28000, website_url: 'https://mistral.ai' },
    { company_id: companyMap['mistral-ai'],    name: 'Mixtral 8x7B',     slug: 'mixtral-8x7b',     description: 'Open-weight MoE model beating Llama 2 70B at half the cost.', category: 'Open Source',  launch_date: '2023-12-08', upvotes: 52000, website_url: 'https://mistral.ai' },
    { company_id: companyMap['hugging-face'],  name: 'Transformers',     slug: 'transformers-lib', description: 'The most popular open-source ML library. 100M+ downloads/month.', category: 'Open Source', launch_date: '2019-10-09', upvotes: 95000, website_url: 'https://huggingface.co/transformers' },
    { company_id: companyMap['hugging-face'],  name: 'Hugging Face Hub', slug: 'hf-hub',           description: '500,000+ models and datasets. The GitHub for AI.',            category: 'Platform',      launch_date: '2020-01-01', upvotes: 80000, website_url: 'https://huggingface.co' },
    { company_id: companyMap['perplexity-ai'], name: 'Perplexity',       slug: 'perplexity-app',   description: 'AI answer engine with real-time web search and citations.',   category: 'Search',        launch_date: '2022-12-07', upvotes: 55000, website_url: 'https://perplexity.ai' },
    { company_id: companyMap['cursor'],        name: 'Cursor Editor',    slug: 'cursor-editor',    description: 'AI-first code editor with tab completion and chat.',           category: 'IDE',           launch_date: '2023-03-14', upvotes: 62000, website_url: 'https://cursor.com' },
    { company_id: companyMap['elevenlabs'],    name: 'ElevenLabs Voice', slug: 'elevenlabs-voice', description: 'Clone any voice and generate lifelike speech in 30+ languages.', category: 'Voice AI',  launch_date: '2023-01-01', upvotes: 48000, website_url: 'https://elevenlabs.io' },
    { company_id: companyMap['runway'],        name: 'Gen-3 Alpha',      slug: 'gen-3-alpha',      description: 'Most advanced AI video generation model from Runway.',        category: 'Video Gen',     launch_date: '2024-06-17', upvotes: 38000, website_url: 'https://runwayml.com' },
    { company_id: companyMap['midjourney'],    name: 'Midjourney v6',    slug: 'midjourney-v6',    description: 'Photorealistic AI image generation via Discord.',              category: 'Image Gen',     launch_date: '2023-12-21', upvotes: 76000, website_url: 'https://midjourney.com' },
    { company_id: companyMap['langchain'],     name: 'LangChain',        slug: 'langchain-framework', description: 'Framework for building LLM-powered apps with chains and agents.', category: 'SDK',   launch_date: '2022-10-25', upvotes: 70000, website_url: 'https://langchain.com' },
    { company_id: companyMap['pinecone'],      name: 'Pinecone Vector DB',slug: 'pinecone-db',     description: 'Managed vector database for similarity search at scale.',     category: 'Database',      launch_date: '2021-03-01', upvotes: 35000, website_url: 'https://pinecone.io' },
    { company_id: companyMap['weights-and-biases'], name: 'Weights & Biases', slug: 'wandb',       description: 'ML experiment tracking, model registry, and evaluation.',    category: 'MLOps',         launch_date: '2018-06-01', upvotes: 40000, website_url: 'https://wandb.ai' },
    { company_id: companyMap['replit'],        name: 'Replit AI',        slug: 'replit-ai',        description: 'AI coding assistant built into the Replit IDE.',              category: 'IDE',           launch_date: '2023-05-01', upvotes: 30000, website_url: 'https://replit.com' },
    { company_id: companyMap['xai'],           name: 'Grok',             slug: 'grok',             description: 'LLM by xAI integrated with X (Twitter) for real-time data.', category: 'Chatbot',       launch_date: '2023-11-04', upvotes: 44000, website_url: 'https://x.ai/grok' },
  ];

  const { data: productRows, error: prErr } = await supabase
    .from('products')
    .insert(products)
    .select();
  if (prErr) { console.error('❌ Products error:', prErr.message); process.exit(1); }
  console.log(`✅ Inserted ${productRows.length} products`);

  // --- Insert Funding Rounds ---
  console.log('\n📥 Inserting funding rounds...');
  const rounds = [
    { company_id: companyMap['openai'],        round_type: 'series-c',   amount: 1000000000,  date: '2023-01-23', lead_investor_id: investorMap['microsoft-ventures'],          co_investors: [investorMap['khosla-ventures']],                                                                         valuation_at: 29000000000, source_url: 'https://techcrunch.com/openai-1b-2023' },
    { company_id: companyMap['openai'],        round_type: 'growth',     amount: 10000000000, date: '2023-10-03', lead_investor_id: investorMap['microsoft-ventures'],          co_investors: [investorMap['tiger-global'], investorMap['andreessen-horowitz']],                                        valuation_at: 80000000000, source_url: 'https://techcrunch.com/openai-10b-2023' },
    { company_id: companyMap['anthropic'],     round_type: 'series-c',   amount: 450000000,   date: '2023-05-23', lead_investor_id: investorMap['spark-capital'],               co_investors: [investorMap['google-ventures'], investorMap['salesforce-ventures']],                                    valuation_at: 5000000000,  source_url: 'https://techcrunch.com/anthropic-450m' },
    { company_id: companyMap['anthropic'],     round_type: 'series-d',   amount: 2000000000,  date: '2023-10-27', lead_investor_id: investorMap['google-ventures'],             co_investors: [investorMap['spark-capital']],                                                                           valuation_at: 20000000000, source_url: 'https://techcrunch.com/anthropic-2b' },
    { company_id: companyMap['anthropic'],     round_type: 'series-d+',  amount: 4000000000,  date: '2024-03-28', lead_investor_id: investorMap['google-ventures'],             co_investors: [investorMap['salesforce-ventures'], investorMap['spark-capital']],                                     valuation_at: 18000000000, source_url: 'https://techcrunch.com/anthropic-4b' },
    { company_id: companyMap['mistral-ai'],    round_type: 'seed',       amount: 113000000,   date: '2023-06-13', lead_investor_id: investorMap['andreessen-horowitz'],         co_investors: [investorMap['lightspeed-venture-partners'], investorMap['nvidia-ventures']],                           valuation_at: 240000000,   source_url: 'https://techcrunch.com/mistral-seed' },
    { company_id: companyMap['mistral-ai'],    round_type: 'series-a',   amount: 415000000,   date: '2023-12-11', lead_investor_id: investorMap['andreessen-horowitz'],         co_investors: [investorMap['lightspeed-venture-partners'], investorMap['salesforce-ventures']],                      valuation_at: 2000000000,  source_url: 'https://techcrunch.com/mistral-415m' },
    { company_id: companyMap['mistral-ai'],    round_type: 'series-b',   amount: 600000000,   date: '2024-06-11', lead_investor_id: investorMap['general-catalyst'],            co_investors: [investorMap['andreessen-horowitz'], investorMap['nvidia-ventures']],                                   valuation_at: 6000000000,  source_url: 'https://techcrunch.com/mistral-600m' },
    { company_id: companyMap['cohere'],        round_type: 'series-c',   amount: 270000000,   date: '2023-06-08', lead_investor_id: investorMap['inovia-capital'] || investorMap['index-ventures'], co_investors: [investorMap['nvidia-ventures'], investorMap['salesforce-ventures']],             valuation_at: 2200000000,  source_url: 'https://techcrunch.com/cohere-270m' },
    { company_id: companyMap['hugging-face'],  round_type: 'series-d',   amount: 235000000,   date: '2023-08-24', lead_investor_id: investorMap['google-ventures'],             co_investors: [investorMap['andreessen-horowitz'], investorMap['salesforce-ventures'], investorMap['nvidia-ventures']], valuation_at: 4500000000, source_url: 'https://techcrunch.com/hf-235m' },
    { company_id: companyMap['scale-ai'],      round_type: 'series-f+',  amount: 1000000000,  date: '2024-05-21', lead_investor_id: investorMap['accel'],                       co_investors: [investorMap['tiger-global'], investorMap['coatue-management']],                                        valuation_at: 13800000000, source_url: 'https://techcrunch.com/scale-1b' },
    { company_id: companyMap['perplexity-ai'], round_type: 'series-b',   amount: 73400000,    date: '2024-01-04', lead_investor_id: investorMap['institutional-venture-partners'] || investorMap['index-ventures'], co_investors: [investorMap['nvidia-ventures'], investorMap['bessemer-venture-partners']], valuation_at: 520000000, source_url: 'https://techcrunch.com/perplexity-73m' },
    { company_id: companyMap['elevenlabs'],    round_type: 'series-b',   amount: 80000000,    date: '2024-01-23', lead_investor_id: investorMap['andreessen-horowitz'],         co_investors: [investorMap['salesforce-ventures'], investorMap['instagram-founders'] || investorMap['benchmark']],   valuation_at: 1100000000,  source_url: 'https://techcrunch.com/elevenlabs-80m' },
    { company_id: companyMap['coreweave'],     round_type: 'series-c',   amount: 1100000000,  date: '2023-05-30', lead_investor_id: investorMap['coatue-management'],           co_investors: [investorMap['nvidia-ventures'], investorMap['accel']],                                                   valuation_at: 7500000000,  source_url: 'https://techcrunch.com/coreweave-1b' },
    { company_id: companyMap['databricks'],    round_type: 'series-i',   amount: 500000000,   date: '2023-09-14', lead_investor_id: investorMap['andreessen-horowitz'],         co_investors: [investorMap['tiger-global'], investorMap['insight-partners']],                                          valuation_at: 43000000000, source_url: 'https://techcrunch.com/databricks-500m' },
    { company_id: companyMap['xai'],           round_type: 'series-b',   amount: 6000000000,  date: '2024-05-26', lead_investor_id: investorMap['andreessen-horowitz'],         co_investors: [investorMap['sequoia-capital'], investorMap['khosla-ventures']],                                       valuation_at: 24000000000, source_url: 'https://techcrunch.com/xai-6b' },
    { company_id: companyMap['harvey-ai'],     round_type: 'series-b',   amount: 100000000,   date: '2024-04-04', lead_investor_id: investorMap['andreessen-horowitz'],         co_investors: [investorMap['sequoia-capital']],                                                                         valuation_at: 1500000000,  source_url: 'https://techcrunch.com/harvey-100m' },
    { company_id: companyMap['cursor'],        round_type: 'series-a',   amount: 60000000,    date: '2024-08-22', lead_investor_id: investorMap['andreessen-horowitz'],         co_investors: [investorMap['benchmark'], investorMap['first-round-capital']],                                          valuation_at: 400000000,   source_url: 'https://techcrunch.com/cursor-60m' },
    { company_id: companyMap['pika-labs'],     round_type: 'series-a',   amount: 55000000,    date: '2023-11-27', lead_investor_id: investorMap['lightspeed-venture-partners'], co_investors: [investorMap['andreessen-horowitz']],                                                                     valuation_at: 500000000,   source_url: 'https://techcrunch.com/pika-55m' },
    { company_id: companyMap['glean'],         round_type: 'series-d',   amount: 200000000,   date: '2024-02-27', lead_investor_id: investorMap['kleiner-perkins'] || investorMap['sequoia-capital'], co_investors: [investorMap['coatue-management'], investorMap['salesforce-ventures']],        valuation_at: 2200000000,  source_url: 'https://techcrunch.com/glean-200m' },
    { company_id: companyMap['writer'],        round_type: 'series-b',   amount: 200000000,   date: '2024-09-03', lead_investor_id: investorMap['andreessen-horowitz'],         co_investors: [investorMap['salesforce-ventures']],                                                                     valuation_at: 1900000000,  source_url: 'https://techcrunch.com/writer-200m' },
  ];

  // Clean up any co_investors arrays that have undefined (from investors that don't exist in our set)
  const cleanedRounds = rounds.map(r => ({
    ...r,
    co_investors: r.co_investors.filter(Boolean),
  }));

  const { data: roundRows, error: rdErr } = await supabase
    .from('funding_rounds')
    .insert(cleanedRounds)
    .select();
  if (rdErr) { console.error('❌ Funding rounds error:', rdErr.message); process.exit(1); }
  console.log(`✅ Inserted ${roundRows.length} funding rounds`);

  // --- Insert News Articles ---
  console.log('\n📥 Inserting news articles...');
  const news = [
    { title: 'OpenAI raises $10B from Microsoft in largest AI deal ever', url: 'https://techcrunch.com/openai-10b', published_at: '2023-10-03T10:00:00Z', source: 'TechCrunch', tag: 'funding', related_company_ids: [companyMap['openai']], summary: 'Microsoft extends its OpenAI partnership with a massive $10B investment, pushing the company valuation to $80B.' },
    { title: 'Anthropic closes $4B round led by Google', url: 'https://techcrunch.com/anthropic-4b', published_at: '2024-03-28T09:00:00Z', source: 'TechCrunch', tag: 'funding', related_company_ids: [companyMap['anthropic']], summary: 'Google deepens its AI bet with a $4B investment in Anthropic, bringing the total to over $7B.' },
    { title: 'Claude 3.5 Sonnet outperforms GPT-4o on coding benchmarks', url: 'https://techcrunch.com/claude-35', published_at: '2024-06-20T14:00:00Z', source: 'TechCrunch', tag: 'product', related_company_ids: [companyMap['anthropic'], companyMap['openai']], summary: 'Anthropic\'s Claude 3.5 Sonnet sets new records on SWE-bench, outperforming competitors on software engineering tasks.' },
    { title: 'Mistral AI raises $600M Series B at $6B valuation', url: 'https://techcrunch.com/mistral-600m', published_at: '2024-06-11T08:00:00Z', source: 'TechCrunch', tag: 'funding', related_company_ids: [companyMap['mistral-ai']], summary: 'French AI startup Mistral raises a massive round as European AI competition heats up.' },
    { title: 'DeepSeek R1 shocks Silicon Valley with GPT-4 level performance at 5% the cost', url: 'https://techcrunch.com/deepseek-r1', published_at: '2025-01-20T12:00:00Z', source: 'TechCrunch', tag: 'product', related_company_ids: [companyMap['deepseek']], summary: 'Chinese AI lab DeepSeek releases R1, a reasoning model that matches o1 performance for a fraction of the training cost.' },
    { title: 'xAI closes $6B round to challenge OpenAI', url: 'https://techcrunch.com/xai-6b', published_at: '2024-05-26T16:00:00Z', source: 'TechCrunch', tag: 'funding', related_company_ids: [companyMap['xai']], summary: 'Elon Musk\'s xAI raises $6B in Series B to fund Grok development and GPU infrastructure build-out.' },
    { title: 'Cursor raises $60M to build the AI code editor of the future', url: 'https://techcrunch.com/cursor-60m', published_at: '2024-08-22T10:00:00Z', source: 'TechCrunch', tag: 'funding', related_company_ids: [companyMap['cursor']], summary: 'Anysphere raises $60M for Cursor, valuing the AI-first code editor at $400M as developer adoption surges.' },
    { title: 'ElevenLabs hits unicorn status with $80M raise', url: 'https://techcrunch.com/elevenlabs-unicorn', published_at: '2024-01-23T11:00:00Z', source: 'TechCrunch', tag: 'funding', related_company_ids: [companyMap['elevenlabs']], summary: 'Voice AI startup ElevenLabs becomes a unicorn after raising $80M at a $1.1B valuation.' },
    { title: 'OpenAI launches Sora text-to-video model', url: 'https://techcrunch.com/sora-launch', published_at: '2024-02-15T18:00:00Z', source: 'TechCrunch', tag: 'product', related_company_ids: [companyMap['openai']], summary: 'OpenAI previews Sora, capable of generating realistic 60-second videos from text prompts, stunning the creative industry.' },
    { title: 'Scale AI valued at $14B after $1B raise', url: 'https://techcrunch.com/scale-14b', published_at: '2024-05-21T09:00:00Z', source: 'TechCrunch', tag: 'funding', related_company_ids: [companyMap['scale-ai']], summary: 'Data labeling giant Scale AI raises $1B, cementing its position as the key pick-and-shovel play in AI training.' },
    { title: 'Perplexity AI reaches $1B valuation with $73M raise', url: 'https://reuters.com/perplexity-1b', published_at: '2024-01-04T09:00:00Z', source: 'Reuters', tag: 'funding', related_company_ids: [companyMap['perplexity-ai']], summary: 'AI search startup Perplexity becomes a unicorn as users seek alternatives to traditional search engines.' },
    { title: 'Harvey AI raises $100M to bring AI to every law firm', url: 'https://bloomberg.com/harvey-100m', published_at: '2024-04-04T10:00:00Z', source: 'Bloomberg', tag: 'funding', related_company_ids: [companyMap['harvey-ai']], summary: 'Legal AI startup Harvey secures $100M at $1.5B valuation as global law firms race to adopt AI.' },
    { title: 'Hugging Face reaches $4.5B valuation with Google-led round', url: 'https://wired.com/hf-235m', published_at: '2023-08-24T14:00:00Z', source: 'Wired', tag: 'funding', related_company_ids: [companyMap['hugging-face']], summary: 'The AI community platform raises $235M from Google, Salesforce, and Nvidia, validating the open-source AI ecosystem.' },
    { title: 'Mistral releases Mixtral 8x7B open-weight model', url: 'https://techcrunch.com/mixtral-launch', published_at: '2023-12-08T08:00:00Z', source: 'TechCrunch', tag: 'product', related_company_ids: [companyMap['mistral-ai']], summary: 'Mistral drops a surprise open-weight MoE model that beats Llama 2 70B on most benchmarks.' },
    { title: 'Writer raises $200M to build enterprise AI platform', url: 'https://techcrunch.com/writer-200m', published_at: '2024-09-03T11:00:00Z', source: 'TechCrunch', tag: 'funding', related_company_ids: [companyMap['writer']], summary: 'Enterprise AI writing platform Writer raises $200M at $1.9B valuation as Fortune 500 companies adopt AI.' },
    { title: 'Runway Gen-3 Alpha sets new standard for AI video quality', url: 'https://techcrunch.com/gen3-alpha', published_at: '2024-06-17T16:00:00Z', source: 'TechCrunch', tag: 'product', related_company_ids: [companyMap['runway']], summary: 'Runway releases Gen-3 Alpha, a new video generation model with dramatically improved consistency and quality.' },
    { title: 'CoreWeave valued at $19B as AI cloud demand soars', url: 'https://wsj.com/coreweave-19b', published_at: '2023-11-21T10:00:00Z', source: 'Wall Street Journal', tag: 'funding', related_company_ids: [companyMap['coreweave']], summary: 'GPU cloud provider CoreWeave becomes one of the most valuable AI infrastructure companies as demand outpaces supply.' },
    { title: 'Databricks acquires MosaicML for $1.3B to accelerate AI', url: 'https://techcrunch.com/databricks-mosaic', published_at: '2023-07-12T09:00:00Z', source: 'TechCrunch', tag: 'acquisition', related_company_ids: [companyMap['databricks']], summary: 'Databricks makes its largest acquisition to bring efficient LLM training into its data platform.' },
    { title: 'LangChain raises $35M to become the backbone of AI apps', url: 'https://techcrunch.com/langchain-35m', published_at: '2023-10-25T12:00:00Z', source: 'TechCrunch', tag: 'funding', related_company_ids: [companyMap['langchain']], summary: 'LangChain raises its Series A just 12 months after launching, now used by 60,000+ developers.' },
    { title: 'Glean valued at $2.2B as enterprise AI search takes off', url: 'https://techcrunch.com/glean-200m', published_at: '2024-02-27T09:00:00Z', source: 'TechCrunch', tag: 'funding', related_company_ids: [companyMap['glean']], summary: 'Enterprise search platform Glean raises $200M as companies race to surface internal knowledge with AI.' },
    { title: 'AI startup funding hits record $50B in H1 2024', url: 'https://reuters.com/ai-funding-record', published_at: '2024-07-01T08:00:00Z', source: 'Reuters', tag: 'industry', related_company_ids: [companyMap['openai'], companyMap['anthropic'], companyMap['mistral-ai']], summary: 'Venture capital investment in AI companies reached a record $50B in the first half of 2024, more than all of 2023.' },
    { title: 'GPT-4o mini launches as OpenAI\'s most affordable model', url: 'https://techcrunch.com/gpt4o-mini', published_at: '2024-07-18T14:00:00Z', source: 'TechCrunch', tag: 'product', related_company_ids: [companyMap['openai']], summary: 'OpenAI releases GPT-4o mini, targeting cost-sensitive use cases at 15 cents per million input tokens.' },
    { title: 'Cohere targets enterprises with Command R+ model release', url: 'https://venturebeat.com/cohere-command-r', published_at: '2024-04-04T10:00:00Z', source: 'VentureBeat', tag: 'product', related_company_ids: [companyMap['cohere']], summary: 'Cohere launches Command R+, optimized for RAG and complex multi-step reasoning in enterprise settings.' },
    { title: 'Pika Labs raises $55M for AI video generation platform', url: 'https://techcrunch.com/pika-55m', published_at: '2023-11-27T11:00:00Z', source: 'TechCrunch', tag: 'funding', related_company_ids: [companyMap['pika-labs']], summary: 'Pika raises $55M from Lightspeed and others as AI video generation becomes the hottest category in generative AI.' },
    { title: 'Weights & Biases reaches $1.25B valuation for MLOps platform', url: 'https://techcrunch.com/wandb-1b', published_at: '2023-03-01T09:00:00Z', source: 'TechCrunch', tag: 'funding', related_company_ids: [companyMap['weights-and-biases']], summary: 'MLOps startup Weights & Biases becomes a unicorn as every AI team adopts experiment tracking.' },
    { title: 'ElevenLabs launches AI dubbing in 29 languages', url: 'https://techcrunch.com/elevenlabs-dubbing', published_at: '2024-03-19T10:00:00Z', source: 'TechCrunch', tag: 'product', related_company_ids: [companyMap['elevenlabs']], summary: 'ElevenLabs releases automatic video dubbing that clones the original speaker\'s voice in 29 languages.' },
    { title: 'Moonshot AI raises $1B as Chinese LLM race heats up', url: 'https://reuters.com/moonshot-1b', published_at: '2024-02-20T08:00:00Z', source: 'Reuters', tag: 'funding', related_company_ids: [companyMap['moonshot-ai']], summary: 'Chinese AI startup Moonshot raises $1B for Kimi, its long-context LLM, drawing comparisons to Claude and GPT-4.' },
    { title: 'Perplexity Pro launches with $20/month subscription', url: 'https://techcrunch.com/perplexity-pro', published_at: '2024-01-30T12:00:00Z', source: 'TechCrunch', tag: 'product', related_company_ids: [companyMap['perplexity-ai']], summary: 'Perplexity launches its Pro tier giving access to GPT-4, Claude, and real-time search for power users.' },
    { title: 'Together AI raises $102M to democratize open-source AI compute', url: 'https://techcrunch.com/together-102m', published_at: '2024-05-15T09:00:00Z', source: 'TechCrunch', tag: 'funding', related_company_ids: [companyMap['together-ai']], summary: 'Together AI raises $102.5M to build the fastest inference API for open-source models like Llama 3 and Mixtral.' },
    { title: 'AI coding assistants now used by 4 million developers', url: 'https://wired.com/ai-coding-4m', published_at: '2024-08-01T10:00:00Z', source: 'Wired', tag: 'industry', related_company_ids: [companyMap['cursor'], companyMap['codeium'], companyMap['replit']], summary: 'A new survey finds 4 million developers regularly use AI coding assistants, with Cursor emerging as the fastest growing.' },
    { title: 'Anthropic launches Claude for Enterprise with enhanced security', url: 'https://techcrunch.com/claude-enterprise', published_at: '2024-09-17T14:00:00Z', source: 'TechCrunch', tag: 'product', related_company_ids: [companyMap['anthropic']], summary: 'Anthropic releases Claude Enterprise with SSO, audit logs, and 500K context window for large organizations.' },
    { title: 'Midjourney v6 produces photorealistic images indistinguishable from photos', url: 'https://techcrunch.com/midjourney-v6', published_at: '2023-12-21T16:00:00Z', source: 'TechCrunch', tag: 'product', related_company_ids: [companyMap['midjourney']], summary: 'Midjourney\'s v6 model shocks designers and photographers with near-perfect photorealistic output.' },
    { title: 'Synthesia secures $90M to scale AI video avatars globally', url: 'https://techcrunch.com/synthesia-90m', published_at: '2023-06-22T09:00:00Z', source: 'TechCrunch', tag: 'funding', related_company_ids: [companyMap['synthesia']], summary: 'London-based Synthesia raises $90M as enterprises adopt AI video for training and communications at scale.' },
    { title: 'Replit hits 1M paid users as AI coding goes mainstream', url: 'https://techcrunch.com/replit-1m', published_at: '2024-06-10T11:00:00Z', source: 'TechCrunch', tag: 'product', related_company_ids: [companyMap['replit']], summary: 'Replit crosses 1 million paid subscribers, making it one of the largest AI-powered developer platforms.' },
    { title: 'AI21 Labs launches Jamba, world\'s first production-grade Mamba model', url: 'https://techcrunch.com/jamba-launch', published_at: '2024-03-28T09:00:00Z', source: 'TechCrunch', tag: 'product', related_company_ids: [companyMap['ai21-labs']], summary: 'AI21 Labs releases Jamba, combining SSM and Transformer architectures for efficient long-context processing.' },
  ];

  const { data: newsRows, error: nwErr } = await supabase
    .from('news_articles')
    .insert(news)
    .select();
  if (nwErr) { console.error('❌ News error:', nwErr.message); process.exit(1); }
  console.log(`✅ Inserted ${newsRows.length} news articles`);

  // --- Refresh Trending Scores ---
  console.log('\n⚡ Computing trending scores...');
  const { error: trendErr } = await supabase.rpc('refresh_all_trending_scores');
  if (trendErr) { console.error('⚠️  Trending scores error (non-critical):', trendErr.message); }
  else { console.log('✅ Trending scores computed'); }

  // --- Final summary ---
  console.log('\n🎉 Seed complete! Summary:');
  console.log(`   • ${investorRows.length} investors`);
  console.log(`   • ${companyRows.length} companies`);
  console.log(`   • ${founderRows.length} founders`);
  console.log(`   • ${productRows.length} products`);
  console.log(`   • ${roundRows.length} funding rounds`);
  console.log(`   • ${newsRows.length} news articles`);
  console.log('\n✨ Your database is ready. Start building the API!');
}

seed().catch(err => {
  console.error('💥 Seed failed:', err);
  process.exit(1);
});